#!/usr/bin/env bash

TESTS_ROOT=$(readlink -f $(dirname $0))
CCGLIB_ROOT=$(readlink -f $TESTS_ROOT/..)

filename=$(basename $1)
cc -I$CCGLIB_ROOT $1 $CCGLIB_ROOT/cvector/cvector.c $CCGLIB_ROOT/screen/charscreen.c $CCGLIB_ROOT/screen/pixelscreen.c $CCGLIB_ROOT/drawing/general.c -lm -o "${filename%.*}".out
